### ISSUE TITLE
Serious vulnerability exists

### ISSUE THREAD

**Issue by happi0** [Kiprey/WebServer#1]
Directory traversal.

Hackers can gain access to a wealth of sensitive information including configuration files.

For example, here I can read my `/etc/passwd`  use `echo -e "GET /../../../../../etc/passwd HTTP/1.0\r\nHost: 127.0.0.1:3000\r\n\r\n" | nc 127.0.0.1 3000
`

![image](https://user-images.githubusercontent.com/86256628/187823824-39afdec8-426d-413c-ba02-e8b97d94f261.png)

**Comment by Kiprey** [comment]
Thank you for the issue!

The directory traversal vulnerability is a known issue. During the implementation, I did not particularly harden this part, but simply completed the function for the sake of simplicity.

This is the only bug I know. I would appreciate if you can find more interesting bugs. 

> Note: Address sanitizer is enabled by default in WebServer.

If you have any questions or comments, please feel free to reply to this issue, or simply close it.

--
Kiprey
